trigger:
- main

pool:
  default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install --upgrade pipenv
    # Install dependencies as specified in Pipfile.lock; the --deploy flag ensures the Pipfile.lock is honored.
    pipenv install --deploy --ignore-pipfile
  displayName: 'Install Pipenv Dependencies'

# - script: |
#     # Run your application or tests within the Pipenv environment.
#     pipenv run python app.py
#   displayName: 'Run Application'
