trigger:
- none

pool:
  default

steps:
- task: CmdLine@2
  inputs:
    script: |  
      echo Upgrading pipenv and installing dependencies...
      pipenv install --skip-lock
      
      echo Starting CPU usage measurement in background...
      start /B cmd /c "pipenv run python record_cpu_usage.py 60 1 cpu_usage.csv"
      
      echo Starting memory usage measurement in background...
      start /B cmd /c "pipenv run python record_memory_usage.py 60 memory_usage.csv"
      
      echo Capturing start time...
      for /f %%i in ('powershell -NoProfile -Command "([int](Get-Date -UFormat s))"') do set start=%%i
      
      echo Running unit tests...
      pipenv run python tests.py
      
      echo Capturing end time...
      for /f %%i in ('powershell -NoProfile -Command "([int](Get-Date -UFormat s))"') do set end=%%i
      
      set /A duration=end - start
      echo Unit tests took %duration% seconds
      
      (
         echo test_duration,duration
         echo unit_test,%duration%
      ) > test_duration.csv
      
      echo Waiting for background measurement processes to finish...
      timeout /T 65 /NOBREAK
      
      echo Aggregating metrics into combined_metrics.csv...
      type cpu_usage.csv > combined_metrics.csv
      more +1 memory_usage.csv >> combined_metrics.csv
      more +1 test_duration.csv >> combined_metrics.csv
      
      echo Combined metrics:
      type combined_metrics.csv
  displayName: 'Install, Measure, Run Tests, and Aggregate Metrics'
