resources:
  repositories:
    - repository: calculatorRepo
      type: github
      name: Siphosethu-Sidloyi/calculator
      endpoint: Siphosethu-Sidloyi

trigger:
- none

pool:
  default

steps:
- checkout: calculatorRepo
  displayName: 'Checkout Calculator Repository'

- task: CmdLine@2
  inputs:
    script: |
      echo Upgrading pipenv and installing dependencies...
      pip install --upgrade pipenv
      pipenv install --skip-lock
      echo Starting CPU usage measurement in background...
      start /B cmd /c "pipenv run python record_cpu_usage.py --duration 60 --interval 1 --output cpu_usage.csv"
      echo Starting memory usage measurement in background...
      start /B cmd /c "pipenv run python record_memory_usage.py --duration 60 --output memory_usage.csv"
      
      echo Running unit tests and measuring duration...
      for /f "delims=" %%a in ('powershell -NoProfile -Command "(Get-Date -UFormat %s)"') do set start=%%a
      pipenv run python tests.py
      for /f "delims=" %%a in ('powershell -NoProfile -Command "(Get-Date -UFormat %s)"') do set end=%%a
      set /A duration=end - start
      echo Unit tests took %duration% seconds
      (
         echo test_duration,duration
         echo unit_test,%duration%
      ) > test_duration.csv
      
      echo Waiting for background measurement processes to finish...
      timeout /T 65 /NOBREAK
      
      echo Aggregating metrics into combined_metrics.csv...
      type cpu_usage.csv > combined_metrics.csv
      more +1 memory_usage.csv >> combined_metrics.csv
      more +1 test_duration.csv >> combined_metrics.csv
      
      echo Combined metrics:
      type combined_metrics.csv
  displayName: 'Install, Measure, Run Tests, and Aggregate Metrics'
