resources:
  repositories:
    - repository: calculatorRepo
      type: github
      name: Siphosethu-Sidloyi/calculator
      endpoint: Siphosethu-Sidloyi

trigger:
- main

pool:
  default

steps:
- checkout: calculatorRepo
  displayName: 'Checkout Calculator Repository'

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.11'
#     addToPath: true
#   displayName: 'Set Python 3.11'

# - script: |
#     echo "Upgrading pipenv and installing dependencies..."
#     dir
#     pipenv install 
#   displayName: 'Install Dependencies Using Pipenv'

- script: |
    echo "Running unit tests..."
    pipenv run pytest
  displayName: 'Run Unit Tests'

# - script: |
#     echo "Building the application..."
#     # For a Flask application, 'building' might simply be verifying that the app starts.
#     pipenv run python app.py --version || echo "Build verified."
#   displayName: 'Build Application'
