resources:
  repositories:
    - repository: calculatorRepo
      type: github
      name: Siphosethu-Sidloyi/calculator
      endpoint: Siphosethu-Sidloyi

trigger:
- main

pool:
  default

steps:
- checkout: calculatorRepo
  displayName: 'Checkout Calculator Repository'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Change into the repository directory
      #cd "$(Build.SourcesDirectory)/calculatorRepo"
      
      echo "Upgrading pipenv and installing dependencies..."
      #pip install --upgrade pipenv
      pipenv install
      
      # Start CPU usage measurement in the background
      echo "Starting CPU usage measurement in background..."
      pipenv run python record_cpu_usage.py --duration 60 --interval 1 --output cpu_usage.csv &
      
      # Start memory usage measurement in the background
      echo "Starting memory usage measurement in background..."
      pipenv run python record_memory_usage.py --duration 60 --output memory_usage.csv &
      
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd "$(Build.SourcesDirectory)/calculatorRepo"
      echo "Running unit tests and measuring duration..."
      start=$(date +%s)
      pipenv run python tests.py
      end=$(date +%s)
      duration=$((end - start))
      echo "Unit tests took $duration seconds"
      # Optionally, write the duration to a CSV file for later aggregation
      echo "test_duration,duration" > test_duration.csv
      echo "unit_test,$duration" >> test_duration.csv
  displayName: 'Run Unit Tests and Measure Duration'
      
      # Wait for all background processes to finish
      echo "Waiting for background measurement processes to finish..."
      wait
      
      echo "All processes completed."
  displayName: 'Install, Measure, and Run Unit Tests'
