trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Starting memory usage monitoring..."
      python record_memory_usage.py 30 --output memory_usage.csv
      echo "Memory usage monitoring completed. Data saved to memory_usage.csv."
  displayName: 'Monitor Memory Usage'
