resources:
  repositories:
    - repository: calculatorRepo
      type: github
      name: Siphosethu-Sidloyi/calculator
      endpoint: Siphosethu-Sidloyi

trigger:
- none

pool:
  default

steps:
- checkout: calculatorRepo
  displayName: 'Checkout Calculator Repository'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Change into the repository directory
      Set-Location "$(Build.SourcesDirectory)\calculatorRepo"
      
      Write-Host "Upgrading pipenv and installing dependencies..."
      #pip install --upgrade pipenv
      pipenv install
      
      # Start CPU usage measurement as a background job
      Write-Host "Starting CPU usage measurement in background..."
      $cpuJob = Start-Job -ScriptBlock { 
          pipenv run python record_cpu_usage.py --duration 60 --interval 1 --output cpu_usage.csv 
      }
      
      # Start memory usage measurement as a background job
      Write-Host "Starting memory usage measurement in background..."
      $memJob = Start-Job -ScriptBlock { 
          pipenv run python record_memory_usage.py --duration 60 --output memory_usage.csv 
      }
      
      # Run unit tests and measure duration
      Write-Host "Running unit tests and measuring duration..."
      $start = Get-Date
      pipenv run python tests.py
      $end = Get-Date
      $duration = ($end - $start).TotalSeconds
      Write-Host "Unit tests took $duration seconds"
      
      # Create CSV for test duration
      "test_duration,duration" | Out-File -FilePath test_duration.csv -Encoding utf8
      "unit_test,$duration" | Out-File -FilePath test_duration.csv -Append -Encoding utf8
      
      # Wait for background jobs to finish
      Write-Host "Waiting for background measurement processes to finish..."
      Wait-Job -Job $cpuJob, $memJob
      
      Write-Host "Background measurements completed."
      
      # Aggregate all metrics into one CSV file
      Write-Host "Aggregating metrics into combined_metrics.csv..."
      $cpuHeader = Get-Content -Path cpu_usage.csv -First 1
      $cpuData   = Get-Content -Path cpu_usage.csv | Select-Object -Skip 1
      $memData   = Get-Content -Path memory_usage.csv | Select-_
